version: "3"

services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
#      - ./docker/postgres/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    networks:
      - default
      - mortgage_network
    external_links:
      - mortgage-backend-flask
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - postgresdb
    ports:
      - "80:80"
    volumes:
      - ./static/:/static

volumes:
  db-data:

networks:
  mortgage_network:
    name: mortgage_network
    external: true
